import { TechEnum, TechEnumKeys } from '../../components';

export const techs: TechEnumKeys[] = [
  TechEnum.JAVASCRIPT,
  TechEnum.TYPESCRIPT,
  TechEnum.NODE,
  TechEnum.NEST,
  TechEnum.DENO,
  TechEnum.JAVA,
  TechEnum.SPRING_BOOT,
  TechEnum.JAVA_FX,
  TechEnum.REACT,
  TechEnum.TAILWIND,
  TechEnum.GRPC,
  TechEnum.TRPC,
  TechEnum.POSTGRESQL,
  TechEnum.MYSQL,
  TechEnum.MONGODB,
  TechEnum.REDIS,
  TechEnum.JDBC,
  TechEnum.JPA,
  TechEnum.JEST,
  TechEnum.DOCKER,
  TechEnum.AWS,
  TechEnum.HTML,
  TechEnum.CSS,
  TechEnum.TENSORFLOW,
  TechEnum.REACT_NATIVE,
  TechEnum.PRISMA,
  TechEnum.MONOREPO,
];
